export default {
  index: 'Introduction',
  '#': {
    type: 'separator',
  },
  'getting-started': 'Getting Started',
  'core-concepts': 'Core Concepts',
  'views-template': 'Views & Templates',
  'int-locale': 'Internationalization',
  'services-provider': 'Services Provider',
  'database-orm': 'Database',
  'bones-console': 'Bones Console',
  'wordpress-integration': 'WordPress Integration',
  'official-packages': 'Official Packages',
  '##': {
    type: 'separator',
  },
  'core-classes': 'Core Classes',
  'core-plugin-files': 'Core Plugin Files',
  'boilerplates': 'Boilerplates',
  'migrating-to-v2': '⬆️ Migrating to v2',
  '###': {
    type: 'separator',
  },
  helpers: 'Helpers',
  contributing: 'Contributing',
  sponsor: 'Became a Sponsor',
  versioning: 'Versioning',
  'security-vulnerabilities': 'Security Vulnerabilities',
  license: 'License',
  faqs: 'FAQs',
  '####': {
    type: 'separator',
  },
  'release-notes': '📣 Release Notes',
};
